particles_vs2008: ParticleRenderer Class Reference
ParticleRenderer Class Reference
#include <render_particles.h>
Public Types
enum DisplayMode { PARTICLE_POINTS, PARTICLE_SPHERES, PARTICLE_NUM_MODES }
Public Member Functions
ParticleRenderer ()
~ParticleRenderer ()
void setPositions (float *pos, int numParticles)
void setVertexBuffer (unsigned int vbo, int numParticles)
void setColorBuffer (unsigned int vbo)
void display (DisplayMode mode=PARTICLE_POINTS)
void displayGrid ()
void setPointSize (float size)
void setParticleRadius (float r)
void setFOV (float fov)
void setWindowSize (int w, int h)
Protected Member Functions
void _initGL ()
void _drawPoints ()
GLuint _compileProgram (const char *vsource, const char *fsource)
Protected Attributes
float * m_pos
int m_numParticles
float m_pointSize
float m_particleRadius
float m_fov
int m_window_w
int m_window_h
GLuint m_program
GLuint m_vbo
GLuint m_colorVBO
Detailed Description
Definition at line 15 of file render_particles.h.
Member Enumeration Documentation
enum DisplayMode
Enumerator
PARTICLE_POINTS
PARTICLE_SPHERES
PARTICLE_NUM_MODES
Definition at line 28 of file render_particles.h.
         {
             PARTICLE_POINTS,
             PARTICLE_SPHERES,
             PARTICLE_NUM_MODES
         };
Constructor & Destructor Documentation
ParticleRenderer ()
Definition at line 25 of file render_particles.cpp.
References _initGL(), m_numParticles, m_particleRadius, m_pointSize, m_pos, and ParticleRenderer().
Referenced by ParticleRenderer().
     : m_pos(0),
       m_numParticles(0),
       m_pointSize(1.0f),
       m_particleRadius(0.125f * 0.5f),
       m_program(0),
       m_vbo(0),
       m_colorVBO(0)
 {
     _initGL();
 }
~ParticleRenderer ()
Definition at line 37 of file render_particles.cpp.
References m_pos.
 {
     m_pos = 0;
 }
Member Function Documentation
GLuint _compileProgram (const char * vsource, const char * fsource) protected
Definition at line 123 of file render_particles.cpp.
 {
     GLuint vertexShader = glCreateShader(GL_VERTEX_SHADER);
     GLuint fragmentShader = glCreateShader(GL_FRAGMENT_SHADER);
     glShaderSource(vertexShader, 1, &vsource, 0);
     glShaderSource(fragmentShader, 1, &fsource, 0);
     glCompileShader(vertexShader);
     glCompileShader(fragmentShader);
     GLuint program = glCreateProgram();
     glAttachShader(program, vertexShader);
     glAttachShader(program, fragmentShader);
     glLinkProgram(program);
     // check if program linked
     GLint success = 0;
     glGetProgramiv(program, GL_LINK_STATUS, &success);
     if (!success)
     {
         char temp[256];
         glGetProgramInfoLog(program, 256, 0, temp);
         printf("Failed to link program:\n%s\n", temp);
         glDeleteProgram(program);
         program = 0;
     }
     return program;
 }
void _drawPoints () protected
Definition at line 54 of file render_particles.cpp.
Referenced by display().
 {
     if (!m_vbo)
     {
         glBegin(GL_POINTS);
         {
             int k = 0;
             for (int i = 0; i < m_numParticles; ++i)
             {
                 glVertex3fv(&m_pos[k]);
                 k += 4;
             }
         }
         glEnd();
     }
     else
     {
         glBindBufferARB(GL_ARRAY_BUFFER_ARB, m_vbo);
         glVertexPointer(4, GL_FLOAT, 0, 0);
         glEnableClientState(GL_VERTEX_ARRAY);
         if (m_colorVBO)
         {
             glBindBufferARB(GL_ARRAY_BUFFER_ARB, m_colorVBO);
             glColorPointer(4, GL_FLOAT, 0, 0);
             glEnableClientState(GL_COLOR_ARRAY);
         }
         glDrawArrays(GL_POINTS, 0, m_numParticles);
         glBindBufferARB(GL_ARRAY_BUFFER_ARB, 0);
         glDisableClientState(GL_VERTEX_ARRAY);
         glDisableClientState(GL_COLOR_ARRAY);
     }
 }
void _initGL () protected
Definition at line 157 of file render_particles.cpp.
Referenced by ParticleRenderer().
 {
     m_program = _compileProgram(vertexShader, spherePixelShader);
 #if !defined(__APPLE__) && !defined(MACOSX)
     glClampColorARB(GL_CLAMP_VERTEX_COLOR_ARB, GL_FALSE);
     glClampColorARB(GL_CLAMP_FRAGMENT_COLOR_ARB, GL_FALSE);
 #endif
 }
void display (DisplayMode mode = PARTICLE_POINTS)
Definition at line 91 of file render_particles.cpp.
References _drawPoints().
Referenced by display().
 {
     switch (mode)
     {
         case PARTICLE_POINTS:
             glColor3f(1, 1, 1);
             glPointSize(m_pointSize);
             _drawPoints();
             break;
         default:
         case PARTICLE_SPHERES:
             glEnable(GL_POINT_SPRITE_ARB);
             glTexEnvi(GL_POINT_SPRITE_ARB, GL_COORD_REPLACE_ARB, GL_TRUE);
             glEnable(GL_VERTEX_PROGRAM_POINT_SIZE_NV);
             glDepthMask(GL_TRUE);
             glEnable(GL_DEPTH_TEST);
             glUseProgram(m_program);
             glUniform1f(glGetUniformLocation(m_program, "pointScale"), m_window_h / tanf(m_fov*0.5f*(float)M_PI/180.0f));
             glUniform1f(glGetUniformLocation(m_program, "pointRadius"), m_particleRadius);
             glColor3f(1, 1, 1);
             _drawPoints();
             glUseProgram(0);
             glDisable(GL_POINT_SPRITE_ARB);
             break;
     }
 }
void displayGrid ()
void setColorBuffer (unsigned int vbo) inline
Definition at line 23 of file render_particles.h.
Referenced by initParticleSystem().
         {
             m_colorVBO = vbo;
         }
void setFOV (float fov) inline
Definition at line 46 of file render_particles.h.
References m_fov.
Referenced by reshape().
         {
             m_fov = fov;
         }
void setParticleRadius (float r) inline
Definition at line 42 of file render_particles.h.
References m_particleRadius.
Referenced by initParticleSystem().
         {
             m_particleRadius = r;
         }
void setPointSize (float size) inline
Definition at line 38 of file render_particles.h.
References m_pointSize.
         {
             m_pointSize = size;
         }
void setPositions (float * pos, int numParticles)
Definition at line 42 of file render_particles.cpp.
References m_numParticles, and m_pos.
 {
     m_pos = pos;
     m_numParticles = numParticles;
 }
void setVertexBuffer (unsigned int vbo, int numParticles)
Definition at line 48 of file render_particles.cpp.
References m_numParticles.
Referenced by display(), and key().
 {
     m_vbo = vbo;
     m_numParticles = numParticles;
 }
void setWindowSize (int w, int h) inline
Definition at line 50 of file render_particles.h.
References m_window_h, and m_window_w.
Referenced by reshape().
         {
             m_window_w = w;
             m_window_h = h;
         }
Field Documentation
GLuint m_colorVBO protected
Definition at line 73 of file render_particles.h.
float m_fov protected
Definition at line 67 of file render_particles.h.
Referenced by setFOV().
int m_numParticles protected
Definition at line 63 of file render_particles.h.
Referenced by ParticleRenderer(), setPositions(), and setVertexBuffer().
float m_particleRadius protected
Definition at line 66 of file render_particles.h.
Referenced by ParticleRenderer(), and setParticleRadius().
float m_pointSize protected
Definition at line 65 of file render_particles.h.
Referenced by ParticleRenderer(), and setPointSize().
float* m_pos protected
Definition at line 62 of file render_particles.h.
Referenced by ParticleRenderer(), setPositions(), and ~ParticleRenderer().
GLuint m_program protected
Definition at line 70 of file render_particles.h.
GLuint m_vbo protected
Definition at line 72 of file render_particles.h.
int m_window_h protected
Definition at line 68 of file render_particles.h.
Referenced by setWindowSize().
int m_window_w protected
Definition at line 68 of file render_particles.h.
Referenced by setWindowSize().
The documentation for this class was generated from the following files:
render_particles.h
render_particles.cpp