particles_vs2008: integrate_functor Struct Reference
integrate_functor Struct Reference
Public Member Functions
__host__ __device__ integrate_functor (float delta_time)
template<typename Tuple >
__device__ void operator() (Tuple t)
Data Fields
float deltaTime
Detailed Description
Definition at line 40 of file particles_kernel_impl.cuh.
Constructor & Destructor Documentation
__host__ __device__ integrate_functor (float delta_time) inline
Definition at line 45 of file particles_kernel_impl.cuh.
References operator()().
 : deltaTime(delta_time) {}
Member Function Documentation
__device__ void operator() (Tuple t) inline
Definition at line 49 of file particles_kernel_impl.cuh.
References operator()().
Referenced by integrate_functor(), and operator()().
     {
         volatile float4 posData = thrust::get<0>(t);
         volatile float4 velData = thrust::get<1>(t);
         float3 pos = make_float3(posData.x, posData.y, posData.z);
         float3 vel = make_float3(velData.x, velData.y, velData.z);
         vel += params.gravity * deltaTime;
         vel *= params.globalDamping;
         // new position = old position + velocity * deltaTime
         pos += vel * deltaTime;
         // set this to zero to disable collisions with cube sides
 #if 0
         if (pos.x > 1.0f - params.particleRadius)
         {
             pos.x = 1.0f - params.particleRadius;
             vel.x *= params.boundaryDamping;
         }
         if (pos.x < -1.0f + params.particleRadius)
         {
             pos.x = -1.0f + params.particleRadius;
             vel.x *= params.boundaryDamping;
         }
         if (pos.y > 1.0f - params.particleRadius)
         {
             pos.y = 1.0f - params.particleRadius;
             vel.y *= params.boundaryDamping;
         }
         if (pos.z > 1.0f - params.particleRadius)
         {
             pos.z = 1.0f - params.particleRadius;
             vel.z *= params.boundaryDamping;
         }
         if (pos.z < -1.0f + params.particleRadius)
         {
             pos.z = -1.0f + params.particleRadius;
             vel.z *= params.boundaryDamping;
         }
 #endif
                 //odbijanie sie od kuli
 #if 1
                 float xk=pos.x*pos.x;
                 float yk=pos.y*pos.y;
                 float zk=pos.z*pos.z;
                 float r=params.bigradius;//- params.particleRadius;
                 if(xk+yk+zk > r*r + FLT_EPSILON )
                 {
                         r-=params.particleRadius*4;
                         /*vel.x*=params.boundaryDamping;
                         vel.y*=params.boundaryDamping;
                         vel.z*=params.boundaryDamping;*/
                         vel.x=0.0f;
                         vel.y=0.0f;
                         vel.z=0.0f;
                         float theta=atan(pos.z/sqrt(pos.x*pos.x+pos.y*pos.y));
                         float fi=atan(pos.y/pos.x);
                         pos.z=r*sin(theta);
                         float rr=r*cos(theta);
                         pos.x=rr*cos(fi);
                         pos.y=rr*sin(fi);
                 }
 #endif
 //dolna plaszczyzna
 #if 0
         if (pos.y < -1.0f + params.particleRadius)
         {
             pos.y = -1.0f + params.particleRadius;
             vel.y *= params.boundaryDamping;
         }
 #endif
         // store new position and velocity
         thrust::get<0>(t) = make_float4(pos, posData.w);
         thrust::get<1>(t) = make_float4(vel, velData.w);
     }
Field Documentation
float deltaTime
Definition at line 42 of file particles_kernel_impl.cuh.
The documentation for this struct was generated from the following file:
particles_kernel_impl.cuh